### ISSUE TITLE
[BUG] Task "tribe29.checkmk.agent : Create host on server." hangs up

### ISSUE THREAD

**Issue by RafaelKr** [tribe29/ansible-collection-tribe29.checkmk#159]
**Describe the bug**

I just tried to use this role to install the checkmk agent on my server an register it at my checkmk site.

The checkmk agent is installed successfully, but it hangs up at task "Create host on server."

My vars are set similar to this:
```
vars:
  checkmk_agent_version: "2.1.0p12"
  checkmk_agent_edition: cre
  checkmk_agent_protocol: https
  checkmk_agent_server: checkmk.example.com
  checkmk_agent_site: monitoring
  checkmk_agent_user: automation
  checkmk_agent_secret: '<MY_SECRET>'
  checkmk_agent_add_host: 'true'
  checkmk_agent_discover: 'true'
  checkmk_agent_folder: 'My Folder'
```

This is the output I get when running `ansible-playbook -vvv my_playbook.yaml`
```
TASK [tribe29.checkmk.agent : Create host on server.] ********************************************************************************************************************************
task path: /home/my_user/.ansible/collections/ansible_collections/tribe29/checkmk/roles/agent/tasks/main.yml:35
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: my_user
<localhost> EXEC /bin/sh -c 'echo ~my_user && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/my_user/.ansible/tmp `"&& mkdir "` echo /home/my_user/.ansible/tmp/ansible-tmp-1663934876.4857767-36863-111637804248786 `" && echo ansible-tmp-1663934876.4857767-36863-111637804248786="` echo /home/my_user/.ansible/tmp/ansible-tmp-1663934876.4857767-36863-111637804248786 `" ) && sleep 0'
Using module file /home/my_user/.ansible/collections/ansible_collections/tribe29/checkmk/plugins/modules/host.py
<localhost> PUT /home/my_user/.ansible/tmp/ansible-local-3676448y416i9/tmpjrcqeokj TO /home/my_user/.ansible/tmp/ansible-tmp-1663934876.4857767-36863-111637804248786/AnsiballZ_host.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/my_user/.ansible/tmp/ansible-tmp-1663934876.4857767-36863-111637804248786/ /home/my_user/.ansible/tmp/ansible-tmp-1663934876.4857767-36863-111637804248786/AnsiballZ_host.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=<HIDDEN>] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-<HIDDEN> ; /usr/bin/python3 /home/my_user/.ansible/tmp/ansible-tmp-1663934876.4857767-36863-111637804248786/AnsiballZ_host.py'"'"' && sleep 0'
```

**Component Name**

`host`

**Ansible Version**

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/my_user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/my_user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True

```

**Checkmk Version**

```console
e.g. 2.1.0p12 (CRE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
tribe29.checkmk   0.10.0 
```
**Environment**

Local machine: Linux Mint 21 Cinnamon
Details: https://termbin.com/uvdqt

checkmk server and client: Debian 11

**To Reproduce**
2. Run '....'
3. Execute '....'

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**
