### ISSUE TITLE
[BUG] Duplicate CRE install stanza

### ISSUE THREAD

**Issue by garethhumphriesgkc** [tribe29/ansible-collection-tribe29.checkmk#189]
The stanzas at line 54 and 78 of [/roles/agent/tasks/RedHat.yml](https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/edf09d26062c4e13bbeb6533e211c49f693c98c3/roles/agent/tasks/RedHat.yml#L54) are identical:
```
- name: "RedHat Derivates: Install Checkmk CRE Agent."
  become: true
  ansible.builtin.yum:
    name: "{{ checkmk_agent_agent.file.cre }}"
    state: present
    disable_gpg_check: true
  when: checkmk_agent_edition == "cre"
  tags:
    - install-package
```

Looks like a copy+paste where one is meant to be a different type, but maybe they're just straight up dupes?

https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/edf09d26062c4e13bbeb6533e211c49f693c98c3/roles/agent/tasks/RedHat.yml#L54
https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/edf09d26062c4e13bbeb6533e211c49f693c98c3/roles/agent/tasks/RedHat.yml#L78

Also, should this be `Derivatives`, not `Derivates`?
