### ISSUE TITLE
[BUG] folder still not idempotent?

### ISSUE THREAD

**Issue by joernclausen** [tribe29/ansible-collection-tribe29.checkmk#205]
**Describe the bug**
I still get "The path ... already exists" when running a playbook creating a folder twice.

**Component Name**
folder

**Ansible Version**
```console
$ ansible --version
ansible 2.10.16
```

**Checkmk Version**
```console
Checkmk Enterprise Edition 2.1.0p10
```

**Collection Version**
```console
$ ansible-galaxy collection list
tribe29.checkmk   0.13.0
```

**To Reproduce**
```
[group-vars]
roles:
  - role: foo-admin
    folder: Compute
  - role: bar-admin
    folder: .

[playbook]
tasks:
    - name: create folder
      folder:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        path: "{{ item.folder }}/{{ item.role }}"
        title: "{{ item.role }}"
        state: present
      loop: "{{ roles }}"
      delegate_to: localhost
```

**Expected behavior**
skip task on second run

**Actual behavior**
```
TASK [create folder] *********************************************************************************************************
failed: [pspoc -> localhost] (item={'role': 'foo-admin', 'folder': 'Compute'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "Compute", "role": "foo-admin"}, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Path already exists\", \"status\": 400, \"detail\": \"The path \\'compute/foo-admin\\' already exists.\"}', "}
failed: [pspoc -> localhost] (item={'role': 'bar-admin', 'folder': '.'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": ".", "role": "bar-admin"}, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Path already exists\", \"status\": 400, \"detail\": \"The path \\'/bar-admin\\' already exists.\"}', "}
```

**Comment by robin-tribe29** [comment]
Hi @joernclausen, two things from the top of my mind: Your Checkmk is not up-to-date, please update to the latest release, there were some important fixes to the API.

Also, your Ansible is not the most recent one, but that should not be the culprit here.

**Comment by joernclausen** [comment]
Just tried it against "Checkmk Enterprise Edition 2.1.0p16", but the error is the same. I also don't think the older Ansible version is the problem here, idempotence for e.g. contact groups works as expected.

**Comment by msekania** [comment]
@joernclausen, 

have you tried to set folder: `'/'` instead of folder `.` for the second entry?

and could you please try the same example by first putting the `state: absent` just to be sure that that folders are not there and then repeat creation task. (sorry, it might be that you have already tried this)

**Comment by joernclausen** [comment]
I initially had `folder: "/"` (seems more logical), but this fails with
```
failed: [ctrlps -> localhost] (item={'role': 'bar-admin', 'folder': '/'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "/", "role": "bar-admin"}, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: parent\", \"fields\": {\"parent\": [\"\\'//\\' does not match pattern \\'(?:(?:[~\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/]|(?:[~\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/][-_ a-zA-Z0-9.]+)+[~\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/]?)|[0-9a-fA-F]{32})\\'.\"]}}', "}
```
on creation. Using `/Compute` as folder does also work.

When using `state: absent`, all paths (i.e. `Compute`, `/Compute`, `/` and `.`) are accepted (i.e. no error), but the tasks are displayed as "no change needed" (i.e. green color), and no folder gets removed.

**Comment by msekania** [comment]
@joernclausen 

sorry, yes `folder: "/"` shoudl not work, it shoudl be `folder: ""`  works in my case as supposed (the second entry)

as for the first entry I already get errors when I try to create first. strange

**Comment by msekania** [comment]
@joernclausen 

concerning the first issue

you have to first create the folder `foo-admin` and only after that one can create folder `foo-admin/Compute`

one cannot just create nested folders directly, one should follow hierarchy!

**Comment by joernclausen** [comment]
BTW: What is actually the difference between `path` and `title`? I would expect `path` to be the path inside with a folder `title` is to be created, but this does not work. Note that I add the value for `title` (`item.role`) also to the path, otherwise it would not work at all.

**Comment by msekania** [comment]
@joernclausen
title is just an alias name

**Comment by joernclausen** [comment]
> you have to first create the folder `foo-admin` and only after that one can create folder `foo-admin/Compute`

I am trying to create `Compute/foo-admin`, and `Compute` is present all the time. Creating a top-level folder is more problematic at the moment.

**Comment by joernclausen** [comment]
> title is just an alias name

I don't think so. If I use
```
path: "{{ item.folder }}"
````
in my playbook above, the task for creating `Compute/foo-admin` creates a folder `/foo-admin`. If I change it to
```
path: "{{ item.folder }}/bla"
```
it creates `Compute/foo-admin`. Needles to say, `bla` is nonexistent.

**Comment by msekania** [comment]
@joernclausen 

following works for me without an issues, lower case for the folder names and it should start with `'/'` !

```yaml
  roles:
      - role: 'foo-admin'
        folder: '/compute'
      - role: 'bar-admin'
        folder: ''
```

**Comment by msekania** [comment]
> > 
> 
> I don't think so. If I use
> 
> ```
> path: "{{ item.folder }}"
> ```
> 
> in my playbook above, the task for creating `Compute/foo-admin` creates a folder `/foo-admin`. If I change it to
> 
> ```
> path: "{{ item.folder }}/bla"
> ```
> 
> it creates `Compute/foo-admin`. Needles to say, `bla` is nonexistent.

@joernclausen,
What you see in GUI is `title`  (aliase) not the `path`.

**Comment by lgetwan** [comment]
I cannot reproduce the problem. When I run joern's playbook, it tries this:
  - role: foo-admin
    folder: Compute
  - role: bar-admin
    folder: .

1. loop: Creating the folder "/compute/foo_admin" fails, because /compute doesn't exist, yet
2. loop: Creating the folder "/bar-admin" works, because it's created in the main folder. 

If you do your vars like this, it should work:
```
roles:
 - title: Compute
   folder: /compute
 - title: Foo Admin
   folder: /compute/foo-admin
 - title: Bar Admin
   folder: /bar-admin
```
And the playbook like this:
```
  - name: create folder
    folder:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      path: "{{ item.folder }}"
      title: "{{ item.title }}"
      state: present
    loop: "{{ folder_test_roles }}"
    delegate_to: localhost
```
This will create the folders
- /compute
- /compute/foo-admin
- /bar-admin

Their GUI names will be slightly different (=> "title").
