### ISSUE TITLE
[FEED] [help-wanted] [role:agent] Can't add custom host attributes

### ISSUE THREAD

**Issue by mircsicz** [tribe29/ansible-collection-tribe29.checkmk#281]
**Provide your feedback**
I can't add Custom Host attributes to a newly added host.

**Component Name**
agent

**Ansible Version**
```console
$ ansible --version
ansible [core 2.12.5]
  config file = /Users/mircsicz/Nextcloud/ONE/Projekte/IT_XXX/CODE/ansible/ansible.cfg
  configured module search path = ['/Users/mircsicz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/mircsicz/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Dec  7 2022, 10:16:11) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True
```

**Collection Version**
```console
$ ansible-galaxy collection list
# /Users/mircsicz/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.posix     1.5.1
community.general 6.4.0
tribe29.checkmk   0.17.1
```
**Environment**
CheckMK v2.1.0p21 CEE on 22.04
client 22.04

**Screenshots**
[CheckMK Custom Attributes](https://snipboard.io/IiATfc.jpg)
[vars/cmk-agent.yml](https://snipboard.io/kIJueD.jpg)

**Additional context**
I'm adding new hosts using this script:

```
---
- hosts: "{{machines}}"

  become: true
  collections:
    - tribe29.checkmk
  roles:
     - tribe29.checkmk.agent

  vars:
    checkmk_server_edition: cee

  pre_tasks:
  - name: Include user/passwd from vars/cmk-agent.yml
    ansible.builtin.include_vars: vars/cmk-agent.yml
```

But when running it I've to face the following:
```
These fields have problems: attributes\", \"fields\": {\"attributes\": {\"folder\": [\"No such attribute, \\'folder\\'\", \"Tag group name must start with \\'tag_\\'\", \"Unknown field.\"], \"Database\": [\"No such attribute, \\'Database\\'
```
