### ISSUE TITLE
[BUG] The user module currently cannot create automation users due to a mismatch in `auth_type`

### ISSUE THREAD

**Issue by robin-tribe29** [tribe29/ansible-collection-tribe29.checkmk#283]
The user module currently cannot create automation users due to a mismatch in `auth_type`:
```
- name: "Create automation user"
      tribe29.checkmk.user:
        ...
        auth_type: "secret"  # `secret` is not accepted by the REST API, should be `automation` instead
```

_Originally posted by @jherbel in https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues/276#issuecomment-1459691481_
