### ISSUE TITLE
[BUG] host module fails because REST API puts trailing slash now

### ISSUE THREAD

**Issue by elwood218** [tribe29/ansible-collection-tribe29.checkmk#41]
Please verify first that your feedback is not already reported [here](https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues?q=is%3Aissue+sort%3Aupdated-desc).
If possible and useful provide additional information below. This is optional however.

**Provide your feedback**
Beginning with Checkmk `2.1.0b6` the output of getting `current_folder` from REST API has changed. Now a trailing slash is added. So like in my case if the parameter `folder` had no trailing slash the condition `if current_folder != module.params["folder"]:` was failing after `2.1.0b5`. 
I added now a trailing slash and this could also be checked in the role I build but if I am correct then modules like "sychronize" and more also checking that.

**Component Name**

`host`

**Ansible Version**

```console
$ ansible --version
ansible [core 2.12.5]
```

**Collection Version**

```console
$ ansible-galaxy collection list
tribe29.checkmk               0.2.0 (also tested with 0.2.2)
```
**Environment**

Checkmk Version: 2.1.0b5 (WORKING - but maybe that would fail if folder parameter got an trailing slash)
Checkmk Version: 2.1.0b6, 2.1.0b7, 2.1.0b8 (FAILING - fixed by putting a trailing slash into folder variable)

**Screenshots**

**Additional context**

**Comment by robin-tribe29** [comment]
@elwood218 thanks for reporting this issue.
For us to be able to reproduce this, please fill in all the requested information as good as possible.
Thanks!

**Comment by elwood218** [comment]
> @elwood218 thanks for reporting this issue. For us to be able to reproduce this, please fill in all the requested information as good as possible. Thanks!

Done....

**Comment by robin-tribe29** [comment]
@elwood218 Thanks for the update!
However, I cannot reproduce your issue as you described it.
Can you provide a minimal working example, how your configuration looks like?

**Comment by elwood218** [comment]
```
- name: "Add/update/remove host"
  tribe29.checkmk.host:
    server_url: "https://{{ cmk_central }}/"
    site: "{{ cmk_central_site }}"
    automation_user: "{{ cmk_site_user }}"
    automation_secret: "{{ cmk_site_password }}"
    host_name: "{{ cmk_host_name | default(host_name) }}"
    attributes:
      "{{ cmk_host_attributes | default(omit) }}"
    folder: "{{ default_host_folder }}"
    state: "{{ cmk_host_state | default('present') }}"
  delegate_to: localhost
  become: no
  notify:
    - activate changes
```
Working:
```
- set_fact:
    default_host_folder: "/{{meta_project_platform | lower}}/{{meta_customer_pretty|upper|mandatory}}/{{meta_project_short|upper}}/{{site|upper}}/"
```

NOT Working: (DIFFERENCE IS THE TRAILING SLASH)
```
- set_fact:
    default_host_folder: "/{{meta_project_platform | lower}}/{{meta_customer_pretty|upper|mandatory}}/{{meta_project_short|upper}}/{{site|upper}}"
```
