### ISSUE TITLE
[BUG] Local variable referenced before assignment

### ISSUE THREAD

**Issue by elwood218** [tribe29/ansible-collection-tribe29.checkmk#45]
Verify first that your issue is not already reported [here](https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
Where possible also test if the latest release and main branch are affected too.
Complete all sections as described!

**Describe the bug**

I have tried to create a folder "customer" and in next task I want to create folder "project" under this "customer" folder:

```
- name: "Create customer folder"
  tribe29.checkmk.folder:
    server_url: "https://{{ cmk_central }}/"
    site: "{{ cmk_central_site }}"
    automation_user: "{{ cmk_site_user }}"
    automation_secret: "{{ cmk_site_password }}"
    path: "/{{ meta_project_platform | lower }}/{{ meta_customer_pretty | upper }}"
    title: "{{ meta_customer_pretty }}"
    attributes:
      "{{ CMK_FOLDER_ATTRIBUTES | default(omit) }}"
    state: "present"
  when: >
    meta_project_platform is defined
    and (meta_project_platform | lower is match("mah")
    or meta_project_platform | lower is match("gcp")
    or meta_project_platform | lower is match("aws")
    or meta_project_platform | lower is match("azure"))
  run_once: true
  delegate_to: localhost
  become: no

- name: "Create poject folder"
#  tribe29.checkmk.folder:
  checkmk_folder:
    server_url: "https://{{ cmk_central }}/"
    site: "{{ cmk_central_site }}"
    automation_user: "{{ cmk_site_user }}"
    automation_secret: "{{ cmk_site_password }}"
    path: "/{{ meta_project_platform | lower }}/{{ meta_customer_pretty | upper }}/{{ meta_project_short | upper }}"
    title: "{{ meta_project_short|upper }}"
    attributes:
      order_atom_id: "{{ meta_project_oaid }}"
    state: "present"
  when: >
    meta_project_platform is defined
    and (meta_project_platform | lower is match("mah")
    or meta_project_platform | lower is match("gcp")
    or meta_project_platform | lower is match("aws")
    or meta_project_platform | lower is match("azure"))
  run_once: true
  delegate_to: localhost
  become: no
```

There is also a problem for the first task but this is not important now (will open another issue for that).
But in the second task I get this error:

```
UnboundLocalError: local variable 'body' referenced before assignment
```

The reason for that are following lines (which are also in the host.py for example).
The variable `body` will only be defined when `status == 200` - but in this case the `status` is 500 (i still debugging it and need to find out why it is 500). But you cannot reference body in `else clause` because it is only defined if `status == 200`.

```
def get_current_folder_state(module, base_url, headers):
    current_state = "unknown"
    current_explicit_attributes = {}
    etag = ""

    path_for_url = module.params["path"].replace("/", "~")

    api_endpoint = "/objects/folder_config/" + path_for_url
    url = base_url + api_endpoint

    response, info = fetch_url(module, url, data=None, headers=headers, method="GET")

    if info["status"] == 200:
        body = json.loads(response.read())
        current_state = "present"
        etag = info.get("etag", "")
        extensions = body.get("extensions", {})
        current_explicit_attributes = extensions.get("attributes", {})
        if "meta_data" in current_explicit_attributes:
            del current_explicit_attributes["meta_data"]

    elif info["status"] == 404:
        current_state = "absent"

    else:
        exit_failed(
            module,
           "Error calling API. HTTP code %d. Details: %s. Body: %s"
            % (info["status"], info["body"], body),
#            "Error calling API. HTTP code %d."
#           % (info["status"]),
        )

    return current_state, current_explicit_attributes, etag
```

The commented lines were just for debugging to see which http code I got.

**Component Name**

`folder`

**Ansible Version**

```console
$ ansible --version
ansible [core 2.12.5]
```

**Checkmk Version**

```console
2.1.0b8 (CEE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
tribe29.checkmk               0.2.2
```
**Environment**

**To Reproduce**
See my example in the bug description

**Expected behavior**

The HTTP Error 500 should be thrown.

**Actual behavior**

It tries to show body but it is never defined because HTTP is not 200 for getting current folder

**Screenshots**

**Additional context**
