### ISSUE TITLE
[BUG] Since version 2.1.0p5 modules not working anymore

### ISSUE THREAD

**Issue by elwood218** [tribe29/ansible-collection-tribe29.checkmk#78]
**Describe the bug**

Folders cannot be created because of changes in the API since 2.1.0p5

```
fatal: [Host1 -> localhost]: FAILED! => changed=false
  msg: 'Error calling API. HTTP code 400. Details: b''{"title": "Bad Request", "status": 400, "detail": "These fields have problems: parent", "fields": {"parent": ["The folder \''/blub/blub/bla\'' could not be found."]}}'', '
```

**Component Name**

`folder`, maybe also `host` 

**Ansible Version**

```console
$ ansible --version
ansible [core 2.12.5]

```

**Checkmk Version**

```console
2.1.0p5 (CEE) and 2.1.0p6
```

**Collection Version**

```console
$ ansible-galaxy collection list
tribe29.checkmk               0.5.0
```
**Environment**

**To Reproduce**

```
- name: "Create site folder"
  tribe29.checkmk.folder:
    server_url: "https://{{ cmk_central }}/"
    site: "{{ cmk_central_site }}"
    automation_user: "{{ cmk_site_user }}"
    automation_secret: "{{ cmk_site_password }}"
    attributes:
      labels:
        test: "test123"
    path: "/BLUB/blub/BLA/FOO"
    title: "Foo"
    state: "present"
  run_once: true
  delegate_to: localhost
  become: no
  notify:
    - activate changes
 ```

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

Please remove the `.lower()` in following line on folder.py. Please also check host.py.

```
ba36a79b (Lars Getwan    2022-03-11 14:29:03 +0100 125)     return str(p.parent).lower(), p.name
```
