### ISSUE TITLE
[BUG] idempotency not working for hosts and folders

### ISSUE THREAD

**Issue by drz9** [tribe29/ansible-collection-tribe29.checkmk#85]
**Describe the bug**
When I am trying to create a folder without trailing slash e.g.:  `path: "/folder"` the run will say "ok", but the folder is not being created. If I use trailing slash e.g.  `path: "/folder/"`, the folder is being created.
But in the next run, this exact same task is going to fail with error:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Path already exists\", \"status\": 400, \"detail\": \"The path \\'/folder\\' already exists.\"}', "}`
This can be worked around by removing the trailing slash in the code.

Creating hosts does not seem to be idempotent, as the host is being created at the first run, but subsequent runs are throwing errors:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Invalid move action\", \"status\": 400, \"detail\": \"The host is already part of the specified target folder\"}', "}
`
**Component Name**
 `folder`
  `host`

**Ansible Version**
```
ansible --version
ansible [core 2.13.1]
```

**Checkmk Version**

`2.1.0p2 (CME)`

**Collection Version**
`0.5.0`

**Environment**
`python 3.8.2`

**To Reproduce**
Run the same playbook multiple times:

```
---
- hosts: localhost
  gather_facts: 'no'
  
  collections:
    - tribe29.checkmk

  tasks:
    - name: "Create folder"
      folder:
        server_url: "https://checkmk"
        site: "mysite"
        automation_user: "automation"
        automation_secret: "secret"
        path: "/folder"
        title: "Folder"
        state: "present"
      run_once: 'true'
      delegate_to: localhost
    - name: "Create a host."
      tribe29.checkmk.host:
        server_url: "https://checkmk/"
        site: "mysite"
        automation_user: "automation"
        automation_secret: "secret"
        host_name: "test_host"
        folder: "/"
        state: "present"
      delegate_to: localhost
      run_once: 'true'
```

**Expected behavior**
Folder and Host being created, subsequent runs being "ok" in terms of ansible idempotency

**Actual behavior**
subsequent runs failing
